CREATE TABLE BOOK (
    ISBN VARCHAR(13) NOT NULL,
    Title VARCHAR(50),
    Author VARCHAR(40),
    Publisher VARCHAR(30),
    Genre VARCHAR(15),
    Price DOUBLE(4, 2),
    Available_copies INT(3),
    PAGES INT(3),
    UNIQUE(ISBN),
    PRIMARY KEY(ISBN)
);

CREATE TABLE PUBLISHER(
    ZIP_CODE VARCHAR(5) NOT NULL,
    PUBLISHER_NAME VARCHAR(20),
    PUBLISHER_ADDRESS VARCHAR(30),
    PHONE VARCHAR(10),
    WEBSITE VARCHAR(25),
    UNIQUE(ZIP_CODE),
    PRIMARY KEY(ZIP_CODE)
);

CREATE TABLE CUSTOMER(
    ID VARCHAR(10) NOT NULL,
    FULLNAME VARCHAR(30),
    AGE INT(2),
    UNIQUE(ID),
    PRIMARY KEY(ID)
);

CREATE TABLE CUSTOMER_ORDER(
    ORDER_ID INT(2) NOT NULL,
    ISBN VARCHAR(10) NOT NULL,
    CUSTOMER_ID VARCHAR(10) NOT NULL,
    ORDER_DAY INT(2),
    ORDER_MONTH INT(2),
    ORDER_YEAR INT(4),
    Requested_copies INT(3),
    UNIQUE(ORDER_ID),
    UNIQUE(ISBN),
    UNIQUE(CUSTOMER_ID),
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE BOOKSTORE(
    BOOKSTORE_NAME VARCHAR(20),
    BOOKSTORE_ADDRESS VARCHAR(40),
    BOOKSTORE_ZIP_CODE VARCHAR(5) NOT NULL,
    PHONE INT(10),
    WEBSITE VARCHAR(30),
    UNIQUE(BOOKSTORE_ZIP_CODE),
    PRIMARY KEY (BOOKSTORE_ZIP_CODE)
);

CREATE TABLE PUBLISHER_ORDER(
    Requested_copies INT(3) NOT NULL,
    ISBN VARCHAR(13) NOT NULL,
    BOOKSTORE_ZIP_CODE VARCHAR(5) NOT NULL,
    ID INT(3) NOT NULL,
    ORDER_DAY INT(2),
    ORDER_MONTH INT(2),
    ORDER_YEAR INT(4),
    UNIQUE(ISBN),
    UNIQUE(BOOKSTORE_ZIP_CODE),
    UNIQUE (ID),
    PRIMARY KEY (ID),
    FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN),
    FOREIGN KEY (BOOKSTORE_ZIP_CODE) REFERENCES BOOKSTORE(BOOKSTORE_ZIP_CODE)
);


CREATE TABLE EMPLOYEE (
    ID INT(10) NOT NULL,
    EMPLOYEE_FULLNAME VARCHAR(40),
    PRIMARY KEY(ID),
    UNIQUE(ID)
);

INSERT INTO BOOKSTORE VALUES("Public", "charilaou trikoupi 123, Nea Erythraia", "14563", " 2106257550", "Public.gr");
INSERT INTO EMPLOYEE VALUES("5912348401", "Paulos Anastasiou");

INSERT INTO BOOK VALUES("9789606232237", "DUNE", "Frank Hebert", "Anubis", "Science Fiction", 20.99, 10, 628);
INSERT INTO BOOK VALUES("9789600404388", "Lord of the rings, return of the king", "Tolkien J. R. R.", "Psychogios", "Fantasy", 12.99, 60, 600);
INSERT INTO BOOK VALUES("9789604611324", "C Programming Language", "Brian W. Kerninghan, Dennis M. Ritchie", "Kleidarithmos", "Computer Science", 19.17, 15, 375);
INSERT INTO BOOK VALUES("9789606450327", "The crow", "Stephen King", "Kleidarithmos", "Science Fiction", 26.91, 20, 1440);
INSERT INTO BOOK VALUES("9789606450099", "The institute", "Stephen King", "Kleidarithmos", "Crime Fiction", 12.39, 50, 632);

INSERT INTO PUBLISHER VALUES(10433, "Anubis", "Solomou 39, Athina", "2103832044","anubis.gr");
INSERT INTO PUBLISHER VALUES(14452, "Psychogios", "Tatoiou 121, Metamorphosi", "2102804800","psichogios.gr");
INSERT INTO PUBLISHER VALUES(14433, "Kleidarithmos", "Marni 8, Athina", "2103832044","klidarithmos.gr");
INSERT INTO PUBLISHER VALUES(11472, "Metaixmio", "Ippokratous 118, Athina", "2113003500","metaixmio.gr");
INSERT INTO PUBLISHER VALUES(10681, "Kastaniotis", "Themistokleous 104, Athina", "2103301208","kastaniotis.com");

INSERT INTO CUSTOMER VALUES("433843543", "Myron Harrakis", 34);
INSERT INTO CUSTOMER VALUES("859481230", "Argyris Contides", 21);
INSERT INTO CUSTOMER VALUES("917345020", "Demetrios Pipoulis", 37);
INSERT INTO CUSTOMER VALUES("176501502", "Nicolaos Xenopoulos", 64);
INSERT INTO CUSTOMER VALUES("591059124", "Manos Mellou", 19);

INSERT INTO CUSTOMER_ORDER VALUES(1, "9789604611324", "917345020", 19, 4, 6, 2021, 1);
INSERT INTO CUSTOMER_ORDER VALUES(2, "9789606450327", "591059124", 19, 4, 6, 2021, 1);

BEGIN
SELECT b.available_quantities, b.ISBN
FROM CUSTOMER_ORDER c, BOOK b, BOOKSTORE bo
IF b.available_quantities == 0
BEGIN 
    SET b.available_quantities = 1;
    INSERT INTO PUBLISHER_ORDER VALUES(b.available_quantities, b.ISBN, BOOKSTORE.bo, c.ORDER_DAY, c.ORDER_MONTH, c.ORDER_YEAR);
END
END

SELECT MAX(Price) FROM BOOK;
SELECT SUM(Price) FROM BOOK;

SELECT FULLNAME FROM CUSTOMER ORDER BY FULLNAME;
SELECT Title FROM BOOK ORDER BY Title;

SELECT COUNT(Title), Genre FROM BOOK GROUP BY Genre;
SELECT COUNT(ORDER_ID), ORDER_YEAR FROM CUSTOMER_ORDER GROUP BY ORDER_YEAR

SELECT customer.FULLNAME, customer.ID from customer INNER JOIN customer_order ON customer.ID=customer_order.CUSTOMER_ID;
SELECT bookstore.BOOKSTORE_ADDRESS, publisher_order.ID from bookstore JOIN publisher_order ON bookstore.BOOKSTORE_ZIP_CODE=publisher_order.BOOKSTORE_ZIP_CODE;
SELECT customer_order.CUSTOMER_ID, book.title from customer_order LEFT JOIN book ON book.ISBN=customer_order.ISBN;